### ISSUE TITLE
Setup Readthedocs Webhooks

### ISSUE THREAD

**Issue by jakirkham** [LPM-HMS/COSMOS-2.0#13]
It doesn't seem like these are active as I had to manual rebuild the documentation to see the fixes. It would be nice if this were automated. Fortunately, this isn't too difficult to do ( http://docs.readthedocs.org/en/latest/webhooks.html#github ).

**Comment by egafni** [comment]
very cool if it works, i enabled it but didn't test

**Comment by jakirkham** [comment]
Alright, well, normally it just works. If it doesn't, we can open another issue.

**Comment by yassineS** [comment]
@jakirkham how long typically it takes to see the updates?

**Comment by jakirkham** [comment]
Looks like you pushed something @yassineS. Hmm... seems like it is not working then.

**Comment by yassineS** [comment]
Well it might take some time like Jekyll to update. Lets wait and see.

**Comment by egafni** [comment]
at least something happened - it was rebuilt by read the docs 2 hours ago without me doing anything

**Comment by jakirkham** [comment]
Yeah, I did that.

**Comment by jakirkham** [comment]
Sure, waiting sounds fine.

**Comment by egafni** [comment]
Wow now authorization required to initiate a rebuild?  I checked again and it should be setup correctly.  One can always do this:

Post Commit Hook
curl -X POST http://readthedocs.org/build/cosmos-wfm

**Comment by yassineS** [comment]
Well it looks like it does update but it takes its time.
