### ISSUE TITLE
Issue launching main.py

### ISSUE THREAD

**Issue by manonSourdeix** [LPM-HMS/COSMOS-2.0#14]
Hi,
I am trying to use your brilliant COSMOS python library. I have done the install and I am now at the "get started" step. I tried to launch the main.py script and keep getting Syntax errors in your scripts, which I don't think they are :)
I am on CentOs6, python2.6
any idea what I could have done wrong ?

For example when I simply run python 'main.py' -h I get

File "main.py", line 76
execution_params = {n: kwargs.pop(n, None) for n in ['name', 'restart', 'skip_confirm', 'max_cpus', 'max_attempts', 'output_dir']}
^
SyntaxError: invalid syntax
(plateforme)

(plateforme) being the virtual environment I created.

Thanks a lot
Manon

**Comment by egafni** [comment]
That's a python 2.6 limitation, upgrade to 2.7! :)

**Comment by manonSourdeix** [comment]
I was pretty sure it was something related to my python version although in the documentation I read that it is ok for python 2.6. 

I did install Python2.7 version BUT be careful on CentOs6 python2.6 must stay the default one otherwise everything else becomes broken. There is a great explanation here : https://www.digitalocean.com/community/tutorials/how-to-set-up-python-2-7-6-and-3-3-3-on-centos-6-4

CAREFUL to create the new virtual environment mentioning you want to use python 2.7 = 'mkvirtualenv --python=/usr/local/bin/python2.7 VE_name'

Also, I did get an SQLite3 problem. I had to run yum install sqlite-devel and send re run the ./configure of python and the make & make altinstall.

Now the main.py executes with no error. 
Thanks a lot for your quick answer !!

**Comment by egafni** [comment]
Sorry, can you let me know where in the docs python 2.6 is okay?  That is clearly a mistake (it use to be a long time ago, but no longer)

Thanks for sharing how to get things going on CentOS.  I've only tested on Ubuntu.

Just curious, what kind of workflows are you writing?

**Comment by manonSourdeix** [comment]
Hi
I started to read from here https://cosmos.hms.harvard.edu/ and the two links seem to redirect to an old documentation. I started to install from there until I realized something was going wrong and then I found the latest documentation here http://cosmos-wfm.readthedocs.org/en/latest/.

The plan is to write genetic sequencing analysis workflows but on grid computing so I am not sure yet this will actually take place. I am testing on my own computer. What I am not sure while reading your documentation is whether I can launch my already written perl workflow through Cosmos.

I am still at the "getting started" point so I might get back to you with some questions.

**Comment by egafni** [comment]
Thanks for the info.  Cosmos2 only recently was released to the public.  @yassineS is there a timeline for updating the website to point to the new COSMOS?  It'd be nice to avoid this confusion for users sooner than later.

@manonSourdeix:   Very cool!  This is also my field.  Happy to help let me know if you have any questions

**Comment by yassineS** [comment]
The website update will be released in a week or so.

**Comment by manonSourdeix** [comment]
Cool for the website because it was a bit confusing.

@egafni Thank you very much ! I have many other things going on so I will be working on Cosmos here and there. I am first trying to make it work on my own computer and integrate our perl pipeline which I don't know whether this will be straightforward or not at all.
Then the idea would be to do the same but with grid computing. This point might be tricky let's see how it goes. Thanks a lot for the help, it will be with pleasure.

**Comment by egafni** [comment]
Cool, best of luck!
