### ISSUE TITLE
dna-seq is not a valid choice on genomekey v 0.1.0 

### ISSUE THREAD

**Issue by Double-O-ren** [LPM-HMS/COSMOS-2.0#25]
`genomekey -d dna-seq -n 'Test_NGX' /genomekey/ngxbio/ngx_test_1.tsv                                   
/home/genomekey/projects/GenomeKey/ve/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning. warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set 
it to True to suppress this warning.')                                                                                        
usage: genomekey [-h] [--ipdb] <command> ...                                                                                  
genomekey: error: argument <command>: invalid choice: 'dna-seq' (choose from 'resetdb', 'aws', 'initdb', 'shell', 'runweb', 'germline')`

**Comment by egafni** [comment]
genomekey germline not gernomekey dna-seq
