### ISSUE TITLE
Error: Internal Server Error on Indel Realigner intermittently 

### ISSUE THREAD

**Issue by Double-O-ren** [LPM-HMS/COSMOS-2.0#27]
Job started running until spot instance closed. 
restarting was manual 
Resubmitting the job again is not an option through the UI
Clicking on Indel Realigner shows Internal server error intermittently 
Job is not being submitted to the SGD queue

**Comment by Double-O-ren** [comment]
When running the webserver with `genomekey runweb` I get the `drmaa.errors.AlreadyActiveSessionException` error

**Comment by egafni** [comment]
The UI is for debugging and monitoring, it'd be possible to add a restart option but it'd be significant dev time and not likely to happen

Did you restart the cluster?  If so the code updates we made friday evening will be gone which will cause the indel realigner problem.  Sorry, I was unable to update GenomeKeyDeploy this weekend with that fix, but can do tonight if you restarted.

**Comment by Double-O-ren** [comment]
I didn't restart the cluster I added the spot instance. The group gk lost the spot instance in the past day. I also see another group gk2, whats the difference between the two?

**Comment by egafni** [comment]
forgot to tear down the gk2 cluster last night when i was testing the
changes, was just emailing you to ask you to terminate it for me :D

you should be good to go if you terminate & restart gk2 with the new
version of GenomeKeyDeploy

**Comment by egafni** [comment]
sorry, i mean terminate & restart gk

**Comment by Double-O-ren** [comment]
Should I be running 0.1.2? 
Do I need to modify the config file? It points to v 0.1.0 throughout

**Comment by egafni** [comment]
Use 0.1.2 and its config file.  I didn't realize its pointing to anything in the 0.1.1 dir but it should be fine.  Feel free to make a backup of it and update if you like.
