### ISSUE TITLE
File download from a wide range of sources

### ISSUE THREAD

**Issue by yassineS** [LPM-HMS/COSMOS-2.0#29]
This is a great tool to get data from just about any cloud source: https://duck.sh

**Comment by egafni** [comment]
cool, does it do multi-part s3?

**Comment by yassineS** [comment]
They only list Multipart Uploads and Multithreaded downloads from S3. I think this package could be as failsafe option or at least recommended option for users that doesn't use S3.

**Comment by egafni** [comment]
sounds reasonable.  I think this is more of a GenomeKey issue than Cosmos though, and a useful discussion for the Slack channel.  Oren and I have been pretty active on slack/GenomeKey, just in PMs btw.  I'm gonna close this and start a convo there
